### ISSUE TITLE
UX: Open up all menus with currently selected skills to develop when clicking the link "Change skills here" from the /toolbox view.

### ISSUE THREAD

**Issue by paccao** [Greenheart/idg.tools#18]

**Comment by Greenheart** [comment]
Thanks for the suggestion!

The current UX from IDG.tools is outdated.

We're going to use a further improved version of this UX going forward: https://29k.org/inner-development

The plan is to basically filter on one page. And if we do keep multiple pages, your suggestion here will be a really nice one :)

**Comment by Greenheart** [comment]
@paccao What do you think about adding numbers to highlight how many skills you've selected for each category instead? This shows some difference compared to the default view, but it's not too much - you still get the nice overview of all five categories.

Related: Instead of just showing the number, perhaps we should a small label `N selected` on the right side of each IDG category?

What do you think?

![example](https://user-images.githubusercontent.com/6125097/174502145-b827fcaa-7105-4c2e-b370-9efe6d35d53d.png)

**Comment by Greenheart** [comment]
Implemented in https://github.com/Greenheart/idg.tools/commit/6a0320dd45ef3b29cb2da135dc6c06fc29964556

Thanks @paccao and @saranyberg for input! 😄
