### ISSUE TITLE
Redesign to mirror 29k version

### ISSUE THREAD

**Issue by chrismact** [Greenheart/idg.tools#28]
Update design as found in Figma

**Comment by Greenheart** [comment]
Remaining TODOs:
- [ ] Important feature that is currently missing: make tools in the library sort so the most relevant show first. Currently it's only filtering to see if the skill ids match, but the order is not ideal.
- [ ] Maybe use an average relevancy score combining both `score` with `scoreGroup`. This would make the estimate more accurate since the group score currently is completely excluded, but adds a more realistic value from the group sharing.

**Comment by Greenheart** [comment]
This will be fixed with the latest changes from the redesign.
